name: counter_slider
description: Flutter Number counter widget with sliding animations and Material theme colors.
version: 0.1.0
repository: https://github.com/BrianCraig/counter_slider

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0